services:
  postgres:
    networks:
      - default
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - DB_URI=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - SERVER_ADDRESS=0.0.0.0:8080
    depends_on:
      - postgres
    entrypoint:
      - "/app/wait-for.sh"
      - "postgres:5432"
      - "--"
      - "/app/start.sh"
    command:
      - "/app/main"