services:
  postgres:
    networks:
      - default
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    networks:
      - default
    image: redis:alpine
    ports:
      - "6379:6379"
  api:
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_URI=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - SERVER_ADDRESS=0.0.0.0:8080
      - REDIS_URI=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint:
      - "/app/wait-for.sh"
      - "postgres:5432"
      - "--"
      - "/app/start.sh"
    command:
      - "/app/main"
volumes:
  data: