// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: service_simplebank.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	accounts "simplebank/pb/accounts"
	transfers "simplebank/pb/transfers"
	users "simplebank/pb/users"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Simplebank_CreateUser_FullMethodName     = "/pb.Simplebank/CreateUser"
	Simplebank_UpdateUser_FullMethodName     = "/pb.Simplebank/UpdateUser"
	Simplebank_LoginUser_FullMethodName      = "/pb.Simplebank/LoginUser"
	Simplebank_RenewAccess_FullMethodName    = "/pb.Simplebank/RenewAccess"
	Simplebank_VerifyEmail_FullMethodName    = "/pb.Simplebank/VerifyEmail"
	Simplebank_CreateAccount_FullMethodName  = "/pb.Simplebank/CreateAccount"
	Simplebank_ListTransfers_FullMethodName  = "/pb.Simplebank/ListTransfers"
	Simplebank_CreateTransfer_FullMethodName = "/pb.Simplebank/CreateTransfer"
	Simplebank_ListAccounts_FullMethodName   = "/pb.Simplebank/ListAccounts"
	Simplebank_GetAccount_FullMethodName     = "/pb.Simplebank/GetAccount"
	Simplebank_DeleteAccount_FullMethodName  = "/pb.Simplebank/DeleteAccount"
)

// SimplebankClient is the client API for Simplebank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimplebankClient interface {
	CreateUser(ctx context.Context, in *users.CreateUserRequest, opts ...grpc.CallOption) (*users.User, error)
	UpdateUser(ctx context.Context, in *users.UpdateUserRequest, opts ...grpc.CallOption) (*users.User, error)
	LoginUser(ctx context.Context, in *users.LoginUserRequest, opts ...grpc.CallOption) (*users.LoginUserResponse, error)
	RenewAccess(ctx context.Context, in *users.RenewAccessRequest, opts ...grpc.CallOption) (*users.RenewAccessResponse, error)
	VerifyEmail(ctx context.Context, in *users.VerifyEmailRequest, opts ...grpc.CallOption) (*users.VerifyEmailResponse, error)
	CreateAccount(ctx context.Context, in *accounts.CreateAccountRequest, opts ...grpc.CallOption) (*accounts.Account, error)
	ListTransfers(ctx context.Context, in *transfers.ListTransfersRequest, opts ...grpc.CallOption) (*transfers.ListTransfersResponse, error)
	CreateTransfer(ctx context.Context, in *transfers.CreateTransferRequest, opts ...grpc.CallOption) (*transfers.CreateTransferResponse, error)
	ListAccounts(ctx context.Context, in *accounts.ListAccountsRequest, opts ...grpc.CallOption) (*accounts.ListAccountsResponse, error)
	GetAccount(ctx context.Context, in *accounts.GetAccountRequest, opts ...grpc.CallOption) (*accounts.Account, error)
	DeleteAccount(ctx context.Context, in *accounts.DeleteAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type simplebankClient struct {
	cc grpc.ClientConnInterface
}

func NewSimplebankClient(cc grpc.ClientConnInterface) SimplebankClient {
	return &simplebankClient{cc}
}

func (c *simplebankClient) CreateUser(ctx context.Context, in *users.CreateUserRequest, opts ...grpc.CallOption) (*users.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(users.User)
	err := c.cc.Invoke(ctx, Simplebank_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) UpdateUser(ctx context.Context, in *users.UpdateUserRequest, opts ...grpc.CallOption) (*users.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(users.User)
	err := c.cc.Invoke(ctx, Simplebank_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) LoginUser(ctx context.Context, in *users.LoginUserRequest, opts ...grpc.CallOption) (*users.LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(users.LoginUserResponse)
	err := c.cc.Invoke(ctx, Simplebank_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) RenewAccess(ctx context.Context, in *users.RenewAccessRequest, opts ...grpc.CallOption) (*users.RenewAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(users.RenewAccessResponse)
	err := c.cc.Invoke(ctx, Simplebank_RenewAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) VerifyEmail(ctx context.Context, in *users.VerifyEmailRequest, opts ...grpc.CallOption) (*users.VerifyEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(users.VerifyEmailResponse)
	err := c.cc.Invoke(ctx, Simplebank_VerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) CreateAccount(ctx context.Context, in *accounts.CreateAccountRequest, opts ...grpc.CallOption) (*accounts.Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accounts.Account)
	err := c.cc.Invoke(ctx, Simplebank_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) ListTransfers(ctx context.Context, in *transfers.ListTransfersRequest, opts ...grpc.CallOption) (*transfers.ListTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transfers.ListTransfersResponse)
	err := c.cc.Invoke(ctx, Simplebank_ListTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) CreateTransfer(ctx context.Context, in *transfers.CreateTransferRequest, opts ...grpc.CallOption) (*transfers.CreateTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(transfers.CreateTransferResponse)
	err := c.cc.Invoke(ctx, Simplebank_CreateTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) ListAccounts(ctx context.Context, in *accounts.ListAccountsRequest, opts ...grpc.CallOption) (*accounts.ListAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accounts.ListAccountsResponse)
	err := c.cc.Invoke(ctx, Simplebank_ListAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) GetAccount(ctx context.Context, in *accounts.GetAccountRequest, opts ...grpc.CallOption) (*accounts.Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accounts.Account)
	err := c.cc.Invoke(ctx, Simplebank_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simplebankClient) DeleteAccount(ctx context.Context, in *accounts.DeleteAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Simplebank_DeleteAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimplebankServer is the server API for Simplebank service.
// All implementations must embed UnimplementedSimplebankServer
// for forward compatibility.
type SimplebankServer interface {
	CreateUser(context.Context, *users.CreateUserRequest) (*users.User, error)
	UpdateUser(context.Context, *users.UpdateUserRequest) (*users.User, error)
	LoginUser(context.Context, *users.LoginUserRequest) (*users.LoginUserResponse, error)
	RenewAccess(context.Context, *users.RenewAccessRequest) (*users.RenewAccessResponse, error)
	VerifyEmail(context.Context, *users.VerifyEmailRequest) (*users.VerifyEmailResponse, error)
	CreateAccount(context.Context, *accounts.CreateAccountRequest) (*accounts.Account, error)
	ListTransfers(context.Context, *transfers.ListTransfersRequest) (*transfers.ListTransfersResponse, error)
	CreateTransfer(context.Context, *transfers.CreateTransferRequest) (*transfers.CreateTransferResponse, error)
	ListAccounts(context.Context, *accounts.ListAccountsRequest) (*accounts.ListAccountsResponse, error)
	GetAccount(context.Context, *accounts.GetAccountRequest) (*accounts.Account, error)
	DeleteAccount(context.Context, *accounts.DeleteAccountRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSimplebankServer()
}

// UnimplementedSimplebankServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimplebankServer struct{}

func (UnimplementedSimplebankServer) CreateUser(context.Context, *users.CreateUserRequest) (*users.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSimplebankServer) UpdateUser(context.Context, *users.UpdateUserRequest) (*users.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedSimplebankServer) LoginUser(context.Context, *users.LoginUserRequest) (*users.LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedSimplebankServer) RenewAccess(context.Context, *users.RenewAccessRequest) (*users.RenewAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewAccess not implemented")
}
func (UnimplementedSimplebankServer) VerifyEmail(context.Context, *users.VerifyEmailRequest) (*users.VerifyEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedSimplebankServer) CreateAccount(context.Context, *accounts.CreateAccountRequest) (*accounts.Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedSimplebankServer) ListTransfers(context.Context, *transfers.ListTransfersRequest) (*transfers.ListTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransfers not implemented")
}
func (UnimplementedSimplebankServer) CreateTransfer(context.Context, *transfers.CreateTransferRequest) (*transfers.CreateTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransfer not implemented")
}
func (UnimplementedSimplebankServer) ListAccounts(context.Context, *accounts.ListAccountsRequest) (*accounts.ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedSimplebankServer) GetAccount(context.Context, *accounts.GetAccountRequest) (*accounts.Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedSimplebankServer) DeleteAccount(context.Context, *accounts.DeleteAccountRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (UnimplementedSimplebankServer) mustEmbedUnimplementedSimplebankServer() {}
func (UnimplementedSimplebankServer) testEmbeddedByValue()                    {}

// UnsafeSimplebankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimplebankServer will
// result in compilation errors.
type UnsafeSimplebankServer interface {
	mustEmbedUnimplementedSimplebankServer()
}

func RegisterSimplebankServer(s grpc.ServiceRegistrar, srv SimplebankServer) {
	// If the following call pancis, it indicates UnimplementedSimplebankServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Simplebank_ServiceDesc, srv)
}

func _Simplebank_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(users.CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).CreateUser(ctx, req.(*users.CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(users.UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).UpdateUser(ctx, req.(*users.UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(users.LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).LoginUser(ctx, req.(*users.LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_RenewAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(users.RenewAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).RenewAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_RenewAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).RenewAccess(ctx, req.(*users.RenewAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(users.VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_VerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).VerifyEmail(ctx, req.(*users.VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).CreateAccount(ctx, req.(*accounts.CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_ListTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transfers.ListTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).ListTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_ListTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).ListTransfers(ctx, req.(*transfers.ListTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_CreateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(transfers.CreateTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).CreateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_CreateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).CreateTransfer(ctx, req.(*transfers.CreateTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_ListAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).ListAccounts(ctx, req.(*accounts.ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).GetAccount(ctx, req.(*accounts.GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simplebank_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(accounts.DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimplebankServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Simplebank_DeleteAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimplebankServer).DeleteAccount(ctx, req.(*accounts.DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Simplebank_ServiceDesc is the grpc.ServiceDesc for Simplebank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Simplebank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Simplebank",
	HandlerType: (*SimplebankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Simplebank_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Simplebank_UpdateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Simplebank_LoginUser_Handler,
		},
		{
			MethodName: "RenewAccess",
			Handler:    _Simplebank_RenewAccess_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _Simplebank_VerifyEmail_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _Simplebank_CreateAccount_Handler,
		},
		{
			MethodName: "ListTransfers",
			Handler:    _Simplebank_ListTransfers_Handler,
		},
		{
			MethodName: "CreateTransfer",
			Handler:    _Simplebank_CreateTransfer_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _Simplebank_ListAccounts_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _Simplebank_GetAccount_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _Simplebank_DeleteAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_simplebank.proto",
}
