name: ci-test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: simplebank
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_ready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Run migrations
        run: make migrateup
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - name: Test
        run: make test
